# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerText', models.CharField(max_length=100)),
                ('AnswerImg', models.FileField(upload_to='')),
                ('AnswerHasImage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=200)),
                ('QuestionHasImage', models.BooleanField(default=False)),
                ('QuestionImage', models.FileField(upload_to='')),
                ('CorrectAnswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funnyquiz.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizName', models.CharField(max_length=50)),
                ('UseStandardWelcomePage', models.BooleanField(default=True)),
                ('WelcomeMessage', models.CharField(max_length=200)),
                ('WelcomeImage', models.FileField(upload_to='')),
                ('UseStandardResultPage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisitorCount', models.IntegerField()),
                ('CompletionCount', models.IntegerField()),
                ('AvgCorrecteness', models.FloatField()),
                ('StdDev', models.FloatField()),
                ('Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnyquiz.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnyquiz.Quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ParentQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funnyquiz.Question'),
        ),
    ]
