# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('funnyquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='CreatedTime',
            field=models.DateField(default=datetime.datetime(2016, 7, 26, 8, 38, 27, 797368, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='QuizUrl',
            field=models.CharField(default=datetime.datetime(2016, 7, 26, 8, 39, 26, 820533, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
