# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnyquiz', '0002_auto_20160726_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='CorrectAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='IsCorrectAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
