# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnyquiz', '0003_auto_20160801_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='AnswerHasImage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='QuestionImage',
        ),
        migrations.AlterField(
            model_name='answer',
            name='AnswerImg',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='WelcomeImage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
