# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnyquiz', '0004_auto_20160801_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='QuestionHasImage',
        ),
        migrations.AddField(
            model_name='question',
            name='QuestionImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='AnswerImg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='WelcomeImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
